# Copyright 2025 Pixagan Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cards = [
    {'card_type': 'text', 'card_header': 'Artificial Intelligence — Definition', 'content': 'Artificial intelligence (AI) is the capability of computational systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. AI research develops methods and software that enable machines to perceive their environment and use learning and intelligence to take actions that maximize chances of achieving defined goals. Systems that implement these capabilities are often called AIs.'}, 
    {'card_type': 'text', 'card_header': 'High‑profile Applications of AI', 'content': 'Examples include advanced web search engines (e.g., Google Search); recommendation systems (YouTube, Amazon, Netflix); virtual assistants (Google Assistant, Siri, Alexa); autonomous vehicles (e.g., Waymo); generative and creative tools (e.g., ChatGPT, AI art); and superhuman play and analysis in games (e.g., chess, Go). Many AI techniques have become embedded in everyday applications and are no longer labeled as "AI."'}, 
    {'card_type': 'text', 'card_header': 'Subfields, Goals, and Techniques', 'content': 'Traditional AI goals include learning, reasoning, knowledge representation, planning, natural language processing, perception, and robotics support. Researchers use a wide range of techniques such as search and mathematical optimization, formal logic, artificial neural networks, statistics, operations research, and economics. AI also draws on psychology, linguistics, philosophy, neuroscience, and related fields. Some organizations aim to develop artificial general intelligence (AGI) able to perform any cognitive task at least as well as humans.'}, 
    {'card_type': 'table', 'card_header': 'AI Research Timeline (key milestones)', 'content': 'Significant events and shifts in AI history', 'data': 'YearOrPeriod,Event\n1956,AI founded as an academic discipline\n1980s-1990s,Methods developed for dealing with uncertain or incomplete information\nPeriods through history,Cycles of optimism followed by funding declines known as AI winters\n2012,GPUs used to accelerate neural networks leading to deep learning breakthroughs\n2017,Introduction and spread of the transformer architecture\n2020s,AI boom with rapid progress in generative AI and renewed attention to risks and regulation'}, 
    {'card_type': 'text', 'card_header': 'Reasoning and Problem‑Solving', 'content': 'Early AI modeled step-by-step (symbolic) reasoning used by humans for puzzles and logical deduction. Later methods addressed uncertainty using probability and economic concepts. Many algorithms face combinatorial explosion and become impractically slow as problem size grows. Human problem solving often relies on fast intuitive judgments rather than exhaustive deduction. Accurate and efficient general-purpose reasoning remains an open challenge.'}, 
    {'card_type': 'text', 'card_header': 'Knowledge Representation', 'content': 'Knowledge representation and knowledge engineering enable AI programs to answer questions and make deductions about real-world facts. Ontologies define concepts and relationships within a domain. Knowledge bases store objects, properties, categories, relations, events, causes and effects, nested knowledge (what others know), defaults, and other aspects. Major challenges include the vast breadth of commonsense knowledge, its often sub-symbolic nature, and the difficulty of acquiring knowledge for AI systems.'}, 
    {'card_type': 'text', 'card_header': 'Planning and Decision‑Making', 'content': "An agent perceives and acts in the world. Rational agents have goals or preferences and select actions to maximize expected utility. Classical planning assumes known, deterministic action effects while real-world problems require probabilistic reasoning under partial observability. Markov decision processes model transitions and rewards; policies map states to actions. Game theory models interactions among multiple agents. Agents may learn others' preferences or seek information to reduce uncertainty."}, 
    {'card_type': 'table', 'card_header': 'Types of Machine Learning', 'content': 'Common machine learning categories with short descriptions and examples', 'data': 'Type,Description,Examples\nSupervised learning,Learning from labeled training data to predict categories or numeric values,Image classification; house price prediction\nUnsupervised learning,Finding patterns or structure in unlabeled data,Clustering; dimensionality reduction\nReinforcement learning,Learning by trial and reward signals to choose actions,Game playing; robotic control\nTransfer learning,Applying knowledge from one task to improve learning on another task,Pretrained language models fine-tuned for specific tasks\nDeep learning,Using multi-layer artificial neural networks for representation learning and prediction,Image recognition; large language models\nComputational learning theory,Analyzing learning algorithms by sample and computational complexity,Theoretical bounds and guarantees'}, 
    {'card_type': 'text', 'card_header': 'Challenges, Harms, and Ethical Concerns', 'content': 'Rapid advances, especially in generative AI, have exposed unintended consequences and harms, raising ethical concerns about long-term effects and potential existential risks. This has prompted discussions on safety, regulation, and policies to ensure beneficial deployment. Technical challenges include commonsense reasoning, knowledge acquisition, scalability of reasoning methods, and handling uncertainty in real-world decision making.'}
]